import { jsPDF } from 'jspdf';
import type { UserData, Theme } from '../types';

export const generateRecoveryPDF = (userData: UserData, theme: Theme) => {
    const doc = new jsPDF();
    
    // Background Gradient
    const grad = doc.context2d.createLinearGradient(0, 0, 0, 297);
    grad.addColorStop(0, '#020617'); // slate-950
    grad.addColorStop(1, '#1e1b4b'); // indigo-950
    doc.context2d.fillStyle = grad;
    doc.rect(0, 0, 210, 297, 'F');

    // Header with Glow
    doc.setFontSize(40);
    doc.setFont("helvetica", "bold");
    doc.setTextColor('#a5f3fc'); // cyan-200
    doc.text("StudyGem", 105, 50, { align: 'center' });
    doc.setTextColor('#f8fafc'); // slate-50
    doc.text("StudyGem", 105, 50.5, { align: 'center' });


    doc.setFontSize(16);
    doc.setFont("helvetica", "normal");
    doc.setTextColor('#94a3b8'); // slate-400
    doc.text("Your Academic Progress Key", 105, 65, { align: 'center' });

    // Info Box (Glassmorphism)
    doc.setFillColor(255, 255, 255, 0.05);
    doc.setDrawColor(255, 255, 255, 0.2);
    doc.setLineWidth(0.5);
    doc.roundedRect(30, 90, 150, 90, 8, 8, 'FD');

    // Name
    doc.setFontSize(14);
    doc.setTextColor('#94a3b8'); // slate-400
    doc.text("Name:", 45, 110);
    doc.setFontSize(20);
    doc.setTextColor('#f8fafc'); // slate-50
    doc.text(userData.name, 45, 120);

    // Class & Roll
    doc.setFontSize(12);
    doc.setTextColor('#94a3b8'); // slate-400
    doc.text(`Class: ${userData.class} | Roll No: ${userData.rollNumber}`, 45, 135)

    // Study ID with Glow
    doc.setFontSize(14);
    doc.setTextColor('#94a3b8'); // slate-400
    doc.text("Study ID:", 45, 155);
    doc.setFontSize(28);
    doc.setFont("courier", "bold");
    
    // Glow effect for the ID
    doc.setTextColor('#0ea5e9'); // sky-500
    doc.text(userData.userId, 45.5, 168.5);
    doc.setTextColor('#67e8f9'); // cyan-300
    doc.text(userData.userId, 45, 168);
    
    // Instructions
    const instructions = [
        "Keep this document safe. It's your key to accessing your progress.",
        "Use this Study ID to log in on any device.",
    ];
    doc.setFontSize(12);
    doc.setFont("helvetica", "normal");
    doc.setTextColor('#64748b'); // slate-500
    doc.text(instructions, 105, 220, { align: 'center', maxWidth: 180 });
    
    // Watermark
    doc.setFontSize(10);
    doc.setTextColor('#334155'); // slate-700
    doc.text("Generated by StudyGem | A DevDigital Creation", 105, 280, { align: 'center' });

    doc.save(`StudyGem_Recovery_${userData.name}.pdf`);
};